theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
title: "SQUADMAPS: All maps and layers in Squad"
description: "SquadMaps is a site to help Squad players and server admins find their favorite maps. All maps and layers in one place."
url: "https://napster653.github.io/SquadMaps/"
